version: '3.8'

services:
  mysql:
    build: .
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: prachi1999
      MYSQL_DATABASE: prachi
      MYSQL_USER: root
      MYSQL_PASSWORD: prachi1999
