
version: '3.8'

services:
  mysql:
    image: mysql:5.7  # Using official MySQL image
    container_name: mysql
    ports:
      - "3306:3306"  # Exposing MySQL port
    environment:
      MYSQL_ROOT_PASSWORD: prachi1999  # Root password
      MYSQL_DATABASE: prachi  # Default database to create
      MYSQL_USER: root  # MySQL user
      MYSQL_PASSWORD: prachi1999  # Password for MySQL user

  backend:
    build: .  # Path to your backend directory
    container_name: backend
    ports:
      - "5000:5000"  # Expose backend port 5000
    environment:
      DATABASE_URL: mysql://root:prachi1999@mysql:3306/prachi  # Connection string for MySQL
    depends_on:
      - mysql  # Ensure MySQL is started before backend
    command: npm start  # Command to start your backend app
